### ISSUE TITLE
HTM Engine: Allow "day of week" and "weekend" date encoder options

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta-apps#104]
Currently, the only options available when creating a model are `min` & `max`. I would like options for including `day_of_week` and `weekend` for the DateEncoder. Example:

```
{
  "min":0, 
  "max":12,
  "day_of_week": true,
  "weekend": true
}
```

This would be quite useful for traffic analysis, which has obvious weekly patterns.

**Comment by rhyolight** [comment]
@oxtopus How hard do you think this would be? I'm thinking about working on it.

**Comment by oxtopus** [comment]
Should be trivial.  Might actually work as-is.  Let me look...

**Comment by oxtopus** [comment]
You'd have to start at https://github.com/numenta/numenta-apps/blob/master/htmengine/htmengine/adapters/datasource/custom/__init__.py#L284-L291 to extract the values, as is currently done with min/max and translate that into the right arguments in https://github.com/numenta/numenta-apps/blob/master/htmengine/htmengine/adapters/datasource/custom/__init__.py#L314-L316

Seems like a better approach ought to expose a more generic interface such that the user could provide their own full configuration.

**Comment by vitaly-krugl** [comment]
Yes, that would be much better:
> Seems like a better approach ought to expose a more generic interface such that the user could provide their own full configuration.
