### ISSUE TITLE
Subutai Anomaly Issue

### ISSUE THREAD

**Issue by jburman789** [numenta/numenta-apps#21]
I listened to his YouTube talk, downloaded his code on Linux 64 and ran into the error: 

File "/usr/local/lib/python2.7/dist-packages/nupic-0.3.0.dev0-py2.7-linux-x86_64.egg/nupic/engine/__init__.py", line 636, in addRegion
    engine.Network.addRegion(self, name, nodeType, nodeParams)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.3.0.dev0-py2.7-linux-x86_64.egg/nupic/bindings/engine_internal.py", line 1086, in addRegion
    return _engine_internal.Network_addRegion(self, *args, **kwargs)
RuntimeError: Unknown parameter 'coincInputPoolPct' for region 'SP' of type 'py.SPRegion'
Valid parameters are:
   stimulusThreshold
   columnCount
   potentialRadius
   learningMode
   maxBoost
   spatialImp
   topDownMode
   activeOutputCount
   breakPdb
   spLearningStatsStr
   breakKomodo
   inputDimensions
   numActiveColumnsPerInhArea
   minPctOverlapDutyCycle
   logPathOutputDense
   globalInhibition
   spInputNonZeros
   columnDimensions
   logPathInput
   logPathOutput
   localAreaDensity
   synPermConnected
   synPermInactiveDec
   inputWidth
   spVerbosity
   denseOutput
   inferenceMode
   dutyCyclePeriod
   sparseCoincidenceMatrix
   anomalyMode
   synPermActiveInc
   seed
   spOverlapDistribution
   minPctActiveDutyCycle
   spOutputNonZeros
   potentialPct
   self

Any advice would be appreicated ... thanks in advance

**Comment by rhyolight** [comment]
I answered this question on our mailing list: http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-June/011136.html

**Comment by jburman789** [comment]
Thanks for the corrections ... I will try them ...

I downloaded the following code from GitHub that failed:

           https://github.com/subutai/nupic.subutai

**Comment by jburman789** [comment]
I do not understand the required corrections to the Subutai anomaly code described at: http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-June/011136.html
Where do I make these corrections?  I grep'd for the keywords suggested and found nothing except in sp_spooler.py where there is a reference to inputShape?  Please advise, thanks

**Comment by MauricioRoman** [comment]
Hi I applied the changes suggested above to the model params in my fork of nupic.subutai, but now I get the error:

RuntimeError: Unknown parameter 'randomSP' for region 'SP' of type 'py.SPRegion'
