### ISSUE TITLE
Making grok zabbix compatible

### ISSUE THREAD

**Issue by felippemr** [numenta/numenta-apps#326]
Hi there!

Guys, Ioved grok! But my metrics are on zabbix! :(
How can I contribute with your project and develop a zabbix adapter?

Thanks!

**Comment by jcasner** [comment]
I'm not terribly familiar with Zabbix.  From looking at it, it appears there's a pretty well documented API [1] to retrieve data.  You may want to take a look at the Cloudwatch Adapter [2] to get an idea for how to build out a new data adapter.  These adapters get called by the metric_collector service [3] to collect data from external services, allowing them to be used for model creation and metric monitoring.

You may also want to check out http://grokstream.com - Avik partners has recently licensed Grok for IT  [4] and will be launching the Grok 2.0 Beta in the near future.  If you're looking to have someone else develop the functionality for you, they are probably your best bet and will be launching their commercial application soon after the beta.  Getting in touch with them now to join the beta and provide feedback for their roadmap would be a huge help to them!

[1] https://www.zabbix.com/documentation/2.2/manual/api/reference
[2] https://github.com/numenta/numenta-apps/tree/master/grok/grok/app/adapters/datasource/cloudwatch
[3] https://github.com/numenta/numenta-apps/blob/master/grok/grok/app/runtime/metric_collector.py
[4] http://numenta.com/press/numenta-announces-licensing-of-grok-for-it-to-avik-partners.html
