### ISSUE TITLE
Modifying the model parameters

### ISSUE THREAD

**Issue by donders** [numenta/numenta-apps#499]
The [README](https://github.com/numenta/numenta-apps/tree/master/htmengine#creating-a-model) is unclear about exactly what parameters you can offer to HTM Engine. Am I free to offer a complete set of model parameters, or is it limited to the parameters that are in the example?

**Comment by rhyolight** [comment]
AFAIK, the only things you can provide to the HTM Engine are min/max values for the input data stream. All other model params are canned and preconfigured for scalar anomaly detection.

**Comment by rhyolight** [comment]
@donders see also https://github.com/numenta/numenta-apps/issues/104.  If you would like to specify complete model params, I assume you also want to get predictions? That is not currently possible. If you want this functionality, please create a new issue. Thanks!
