### ISSUE TITLE
HTM Engine should allow users to provide entire model params

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta-apps#503]
Instead of just min/max for the encoder params, I would like to provide the entire model params myself.

**Comment by ryanjmccall** [comment]
OK @rhyolight  this seems approachable. I'm looking at this from the webapp.py point of view. so call permutations_runner whenever a new model is requested. then it would be easy to add an argument to htmengine.adapters.datasource.custom._CustomDatasourceAdapter#monitorMetric and similar adapters. but maybe the swarming takes so long it should be handled in a separate thread..

**Comment by rhyolight** [comment]
There is no swarming in HTM Engine at all, so you provide the model params, and HTM Engine creates a model.

**Comment by ryanjmccall** [comment]
Got it. I see there are 3 DataSourceAdapters -- Custom, Cloudwatch, and Autostack. Would you prefer this change be implemented uniformly for all 3 or should it only focus on Custom which may be the only place where people would want to experiment with passing in swarm params? 

The model spec is currently a dict with top level keys 'modelParams', 'datasource', and 'metricSpec'. I can add another key 'swarmParams' and check for that inside `monitorMetric()`

**Comment by rhyolight** [comment]
I must defer those questions to those will will ultimately review the PR, likely @oxtopus or @vitaly-krugl

**Comment by vitaly-krugl** [comment]
I would recommend focusing on Custom metrics, which is good for experimentations. The others are mote tightly coupled with the HTM-IT application. In fact, if we were re-implementing HTM-IT, we would probably implement it on top of Custom Metrics, as we had later done in Taurus.

**Comment by oxtopus** [comment]
@rhyolight it may help to limit scope somewhat, since `htmengine` only works with a limited set of parameters.  It's not safe to assume that `htmengine` will always work with every technically valid parameter.

**Comment by rhyolight** [comment]
@oxtopus Do you have an idea of the specific params that might cause problems?

**Comment by oxtopus** [comment]
Classification, non-anomaly, or multistep models come to mind, basically anything but a single-step, single-field scalar temporal anomaly model.  Anything but, and results are "unexpected".

**Comment by vitaly-krugl** [comment]
I concur with @oxtopus

**Comment by rhyolight** [comment]
Hm, this is trickier then. @ryanjmccall What do you think about putting in a validation step before creating the model?

**Comment by ryanjmccall** [comment]
@oxtopus so we only have to verify "inferenceType" is "TemporalAnomaly" and "steps" is 1 (or is anomaly restricted to only 1 step?). the steps value appears to occur multiple times 1) in the clParams, 2) the inferenceArgs (where I'm hardcoding to 1 in the monitorMetric), and 3) in the inputRecordSchema (also hardcoded).

**Comment by ryanjmccall** [comment]
@rhyolight I can do something like `htmengine.utils.validate(modelSpec, g_model_spec_schema)` in the `monitorMetric` method -- is that what you had in mind?

**Comment by rhyolight** [comment]
Deferring to @oxtopus / @vitaly-krugl but yes that's the type of thing I was thinking.

**Comment by vitaly-krugl** [comment]
@ryanjmccall, I have some feedback concerning this in your PR #769, with clarifications and references to examples.
