### ISSUE TITLE
Predictions are available as well as anomaly results

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta-apps#504]
@ryanjmccall said:

> My motivation is that on the project I'm working on we found that the anomaly likelihood was unsuitable for certain metrics. Instead we have had some success with using the predicted values in combination with some post processing to produce alerts.

Depends on #503 because model params with the right inference type must be provided by the user.

**Comment by ryanjmccall** [comment]
@rhyolight thx, I'll take a look at this. I'm guessing it might be enough to add a 'prediction' row to the 'metric_data' schema and figure out where that should be populated

**Comment by rhyolight** [comment]
I don't think it's that simple. You'll probably need to update some SQL tables. @oxtopus knows more.

**Comment by ryanjmccall** [comment]
I am going to sketch out all the pieces that will have to change to expose the predicted value in addition to the anomaly scores. I am imagining there will be a new column added to the `metric_data` table for the current predicted value. (alternatively, it could be the previous predicted value, but, in that case, I don't know where the current predicted value would get stored). I have identified this method where the htmengine meets the OPF:

`htmengine.model_swapper.model_runner.ModelRunner#_processInputRow`

In this method there is a line: `r = self._model.run(inputRecord)`

Currently, the r.inferences dict only contains anomaly info like this: `{'anomalyLabel': '[]', 'anomalyScore': 0.0}`. I believe this is b/c the 'inferenceType' is 'TemporalAnomaly'. So one thing I have to figure out is how to coerce the OPF to return the predicted values but still comply with the restriction of HTM engine for TemporalAnomaly models. Do we relax this constraint or is there a way to ask for the prediction even if it's a TemporalAnomaly model? (@vitaly-krugl  @oxtopus)

Changing the metric_data table requires updating a lot of areas. So far I've identified, at the very least, the following changes:
- `htmengine.repository.schema`  (also consider whether to add an index for predicted value column)
- `model_inference_results_msg_schema.json` will require the predict value in the results section
- AnomalyService's `_composeModelInferenceResultsMessage` will have to support the predicted value
- `AnomalyService#_scrubInferenceResultsAndInitMetricData` employs a `MutableMetricDataRow` that would change
- `ModelInferenceResult` in the model swapper interface would have to be extended as well

Well that's a start for today. I'll keep studying the code and update this comment.

**Comment by ryanjmccall** [comment]
@rhyolight I'm struggling to figure out how one would pull the predicted value out of an OPF model with "TemporalAnomaly" inferenceType. I am logging ModelResult structure (in htmengine.model_runner) but don't see the prediction (unless it's sensorInput.dataRow[0] ?) Could you please point me in the right direction as to how to get at the predicted value? thank you

**Comment by rhyolight** [comment]
@ryanjmccall said:
> @rhyolight I'm struggling to figure out how one would pull the predicted value out of an OPF model with "TemporalAnomaly" inferenceType.

Sorry, been ignoring emails for too long. You should be able to simply switch the model type to "TemoralAnomaly" and use it like a "TemoralMultiStep" model as described here:

https://youtu.be/1fU2Mw_l7ro?t=2m51s

**Comment by vitaly-krugl** [comment]
htmengine is really a "time series scalar anomaly detection" engine. We need to tread carefully when adding the new functionality so as not to end up with a mess. For example, the results flow from model-runners to the anomaly service, which post-processes and stores them. It would be confusing if something named "anomaly service" also had to deal with non-anomaly results, such as multi-step predictions. Also, the database schema might get messy. It might be useful to think in terms of refactoring, whereby we could share the logic that makes sense to share, while separating out other concerns.

**Comment by rhyolight** [comment]
@ryanjmccall HTM Engine, like @vitaly-krugl said, was not designed to do prediction at any point. So there could be many barriers to enabling that functionality. I'm not sure what they are. 😕

**Comment by ryanjmccall** [comment]
@rhyolight OK I found the issue. The current best anomaly parameters (`nupic/src/nupic/frameworks/opf/common_models/anomaly_params_random_encoder/best_single_metric_anomaly_params_cpp.json`), which are used by htmengine, disable the classifier with the parameter `clEnable`. 

I suppose it would be simplest to add a parameter to the application.conf named something like 'includePredictions'. This would globally control the expectation of predicted value(s) at the various locations of concern across htmengine. Each location would respond differently based on its value. E.g., the monitorMetric() method would inject `clEnable: True` (when `includePredictions: True`) for each new metric request of a particular run instance.

**Comment by ryanjmccall** [comment]
FYI, I made a conscious decision to use `multiStepBestPredictions` over `multiStepPredictions`. The latter contains more information, however, this level of detail struck me as inappropriate for HTM engine where the goal is to provide scaling and simplicity. And, perhaps, if you're messing around with classifier-level data then that should be done as an experiment. OTOH perhaps there are good reasons for providing the full `multiStepPredictions`.  I'm happy enough with `multiStepBestPredictions` but it could be changed... @rhyolight @vitaly-krugl @oxtopus

**Comment by vitaly-krugl** [comment]
@ryanjmccall, what is the benefit of making the predictions available in addition to anomaly results? When you opened this ticket, you indicated that you wanted to add this feature, but didn't explain why it's useful. Could you please augment the opening description?

**Comment by ryanjmccall** [comment]
@vitaly-krugl (I don't own the opening comment, can @rhyolight update his?) My motivation is that on the project I'm working on we found that the anomaly likelihood was unsuitable for certain metrics. Instead we have had some success with using the predicted values in combination with some post processing to produce alerts. I believe there was at least one other person on the mailing list that wanted predictions too, but I don't recall why.

**Comment by rhyolight** [comment]
> can @rhyolight update his?

Yes he can.
