### ISSUE TITLE
Docker files gone?

### ISSUE THREAD

**Issue by passiweinberger** [numenta/numenta-apps#601]
the docker-build-all.sh script looks for all the Dockerfiles in the repos, which are not there? 

and the Dockerhub entry: https://hub.docker.com/r/oxtopus/numenta-apps/ 
is also only for the new imbu thing... ? 

Nothing of the old stuff left? :D

**Comment by vitaly-krugl** [comment]
@oxtopus, could you chime in? thx

**Comment by oxtopus** [comment]
We removed several Dockerfile entries recently.  We aren't using/maintaining them, and they aren't documented well, if at all.  As such, we should have removed docker-build-all.sh, too.  Imbu, however, does have an actively used and maintained Dockerfile, documented at https://github.com/numenta/numenta-apps/blob/master/imbu/README.md#run-imbu-in-docker

**Comment by passiweinberger** [comment]
Is it possible to recover the old files though? I found docker extremely useful back then and as I changed my laptop I lost them 😖

Also I guess in total it can make a lot of sense to have them stick. If nothing too much of a workload...

--Pascal 



Best,

Pascal Weinberger 

____________________________

BE THE CHANGE YOU WANT TO SEE IN THE WORLD ...


PLEASE NOTE:  This email and any file transmitted are strictly confidential and/or legally privileged and intended only for the person(s) directly addressed. If you are not the intended recipient, any use, copying, transmission, distribution, or other forms of dissemination is strictly prohibited. If you have received this email in error, please notify the sender immediately and permanently delete the email and files, if any.
Please consider the environment before printing this message.

**Comment by oxtopus** [comment]
They were removed in https://github.com/numenta/numenta-apps/pull/590

You can recover them by checking them out from an earlier commit.
