### ISSUE TITLE
Unicorn - Add clean:db:win

### ISSUE THREAD

**Issue by marionleborgne** [numenta/numenta-apps#620]
Remember to add an entry `clean:db:win` in `package.json` (and to update `README`) to clean DB on windows.

cc @lscheinkman

**Comment by go-bears** [comment]
is this issue still open?

**Comment by rhyolight** [comment]
@go-bears Yes, are you thinking of working on it? Do you need some guidance from @marionleborgne?

**Comment by go-bears** [comment]
@rhyolight yes, I would need guidance b/c I'm not running windows. I'd be happy to update the package.json with the ' clean:db:win' key, but i'd need help figuring out the value to that goes with the key.

**Comment by go-bears** [comment]
@rhyolight yes, I would need guidance b/c I'm not running windows. I'd be happy to update the package.json with the ' clean:db:win' key, but i'd need help figuring out the value to that goes with the key.

**Comment by rhyolight** [comment]
@go-bears If you don't have a Windows machine to test this on, maybe this is not the best issue to help with?
