### ISSUE TITLE
taurus: unable to create db

### ISSUE THREAD

**Issue by cbaranski** [numenta/numenta-apps#655]
Problem installing Taurus on the step “taurus-create-db” - see attached screenshot.
Sent to numenta support.

![taurus db issue](https://cloud.githubusercontent.com/assets/8237376/13258364/bc5fb52e-da07-11e5-9371-fa87a1d9e004.png)

**Comment by vitaly-krugl** [comment]
I'll update htmengine/README.md with an explanation that should help.

**Comment by vitaly-krugl** [comment]
The traceback directs the developer to look for help about APPLICATION_CONFIG_PATH in htmengine/README.md. I improved documentation in the README via #656. That should help.

**Comment by rhyolight** [comment]
Wonderful, thank you Vitaly!

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by vitaly-krugl** [comment]
In case someone is trying to solve the same issue, here is an excerpt from nupic discussion list that takes  this issue through to conclusion via a work-around (for now):

> Hi Vitaly,
Thank you very much. Now I am able to run the script to initialize database
now. Will write an email again if facing any other issues.
Best,
Vannroath


From @vitaly-krugl:

>Hi Vannroath,
I was able to reproduce the problem that you¹re experiencing on Ubuntu
64bit running in VirtualBox. In taurus/taurus/engine/__init__.py, try
changing the string parameter taurus to taurus.engine in the statement
distribution = get_distribution("taurus")

**Comment by vitaly-krugl** [comment]
NOTE: I am reopening this issue, since it's not really fixed. My prior comment merely describes a work-around for the bug in Taurus.
