### ISSUE TITLE
CustomDatasourceAdapter#monitorMetric should delete metricId when exception occurs

### ISSUE THREAD

**Issue by ryanjmccall** [numenta/numenta-apps#833]
The call to create the metricId in the database could be followed by an exception producing an inconsistent state.

**Comment by ryanjmccall** [comment]
@vitaly-krugl

**Comment by vitaly-krugl** [comment]
@ryanjmccall, did you mean "The call **to** create the metricId in the database could be **followed** by an exception producing an inconsistent state."?

**Comment by ryanjmccall** [comment]
@vitaly-krugl correct, I wrote that in hurry this morning. thx
