### ISSUE TITLE
Add type of the offending object to the assertion message when typecheck of anomaly score fails

### ISSUE THREAD

**Issue by vitaly-krugl** [numenta/numenta-apps#891]
model_swapper_interface.py asserts:

```
      assert isinstance(anomalyScore, (int, long, float)), (
        "Expected numeric anomaly score with status=0, but got: " +
        repr(anomalyScore))
```

A user reported an unexpected assertion failure: `AssertionError: Expected numeric anomaly score with status=0, but got: 1.0)` in an HTM Forum post https://discourse.numenta.org/t/my-installation-suddenly-failed-with-asertionerror-message/1389.

It would have been helpful for root-causing if the assertion message included the type of the offending object.

**Comment by oxtopus** [comment]
The assertion will fail with certain `numpy` floats. e.g. 

```
>>> repr(numpy.float(1.0)), isinstance(numpy.float(1.0), (int, long, float))
('1.0', True)
>>> repr(numpy.float(1.0)), isinstance(numpy.float32(1.0), (int, long, float))
('1.0', False)
```

Probably better to handle it gracefully rather than address debug pain points.  This kind of problem happens on occasion.
